# -*- coding: utf-8 -*-
"""
Created on Tue Jan  2 15:14:09 2018

@author: jinyx
"""
s01_file_path = './data_preprocessed_python/s01.dat'
s02_file_path = './data_preprocessed_python/s02.dat'
s03_file_path = './data_preprocessed_python/s03.dat'
s04_file_path = './data_preprocessed_python/s04.dat'
s05_file_path = './data_preprocessed_python/s05.dat'
s06_file_path = './data_preprocessed_python/s06.dat'
s07_file_path = './data_preprocessed_python/s07.dat'
s08_file_path = './data_preprocessed_python/s08.dat'
s09_file_path = './data_preprocessed_python/s09.dat'
s10_file_path = './data_preprocessed_python/s10.dat'
s11_file_path = './data_preprocessed_python/s11.dat'
s12_file_path = './data_preprocessed_python/s12.dat'
s13_file_path = './data_preprocessed_python/s13.dat'
s14_file_path = './data_preprocessed_python/s14.dat'
s15_file_path = './data_preprocessed_python/s15.dat'
s16_file_path = './data_preprocessed_python/s16.dat'
s17_file_path = './data_preprocessed_python/s17.dat'
s18_file_path = './data_preprocessed_python/s18.dat'
s19_file_path = './data_preprocessed_python/s19.dat'
s20_file_path = './data_preprocessed_python/s20.dat'
s21_file_path = './data_preprocessed_python/s21.dat'
s22_file_path = './data_preprocessed_python/s22.dat'
s23_file_path = './data_preprocessed_python/s23.dat'
s24_file_path = './data_preprocessed_python/s24.dat'
s25_file_path = './data_preprocessed_python/s25.dat'
s26_file_path = './data_preprocessed_python/s26.dat'
s27_file_path = './data_preprocessed_python/s27.dat'
s28_file_path = './data_preprocessed_python/s28.dat'
s29_file_path = './data_preprocessed_python/s29.dat'
s30_file_path = './data_preprocessed_python/s30.dat'
s31_file_path = './data_preprocessed_python/s31.dat'
s32_file_path = './data_preprocessed_python/s32.dat'
